### ISSUE TITLE
求教为什么我这极验文字点选get.php接口返回里面没有CS值

### ISSUE THREAD

**Issue by caster-Q** [ravizhan/geetest-v3-click-crack#1]
{
  "status": "success",
  "data": {
    "spec": "1*1",
    "logo": false,
    "theme_version": "1.2.4",
    "theme": "silver",
    "skin": {
      "id": 1,
      "color": 1
    },
    "static_servers": [
      "captcha-static.xxx.com"
    ],
    "feedback": "",
    "pic": "dist/v202307/0ca4d87b568f4e849613d38731b66183.jpg",
    "image_servers": [
      "captcha-static.xxx.com"
    ],
    "sign": ""
  }
}

**Comment by ravizhan** [comment]
能详细讲讲复现步骤吗，我这边是正常的。

**Comment by caster-Q** [comment]
貌似是版本问题，我这用的极验是老版本的

**Comment by caster-Q** [comment]
貌似是版本问题，我这极验是老版本的：
![image](https://github.com/user-attachments/assets/1a26626c-7e48-4a93-86bc-89a6adfeff6d)

**Comment by ravizhan** [comment]
版本不对肯定用不了啊，都写了是极验第三代

**Comment by caster-Q** [comment]
> 版本不对肯定用不了啊，都写了是极验第三代

可以帮忙研究一下么，有偿

**Comment by ravizhan** [comment]
抱歉，最近没时间
