### ISSUE TITLE
大神，能给出siamese.onnx模型训练的代码贴出来吗

### ISSUE THREAD

**Issue by wxyz0001** [ravizhan/geetest-v3-click-crack#3]
大神，能给出siamese.onnx模型训练的代码贴出来吗？

**Comment by ravizhan** [comment]
就是鸣谢里的 https://github.com/bubbliiiing/Siamese-pytorch

**Comment by wxyz0001** [comment]
可是我是小白，不会修改代码。
能把你的yolo模型和siamese模型训练的代码发一份给我好吗？






我照着代码训练，应该就没问题
希望能收到你的训练代码
我将不胜感激

**Comment by ravizhan** [comment]
没改过代码，就是这两 https://github.com/ultralytics/ultralytics/ https://github.com/bubbliiiing/Siamese-pytorch
